version: "3.9"
   
services:
  web:
    image: "server"
    volumes:
      - static_volume:/code
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code
    ports:
      - "2017:80"
    depends_on:
      - web
volumes:
  static_volume: