version: "3.9"
   
services:
  api:
    image: "interplaytions-server:test"
    volumes:
      - static_volume:/code/midiresult
    ports: 
    - "8000:8000"
    environment:
      DEBUG: "False"
      SECRET_KEY: "v^55^y*nk%38!w^rzychc5mbqaw(rvadv@ic$xz36101am_et!"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  code:
    image: "interplaytions-server-nginx:test"
    volumes:
      - static_volume:/code/midiresult 
    ports:
      - "8001:8001"
    depends_on:
      - api
    environment:
      API_HOST: host.docker.internal
      API_PORT: 8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
  web:
    image: "interplaytions-web:test"
    ports:
      - "80:80"
    environment:
      API_HOST: host.docker.internal
      API_PORT: 8000
      CODE_HOST: host.docker.internal
      CODE_PORT: 8001
    depends_on:
      - code
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  static_volume: